bug_manage/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Web.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register.register, name='register'),
    path('send/sms/', register.send_sms, name='send_sms')

]

Web/models.py
from django.db import models


# Create your models here.

class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮箱',max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=32)

Web/views.py
import random

# Create your views here.
from django.shortcuts import HttpResponse, render

from Web.utils.ModelForm import *
from Web.utils.tencent.send_SMS import send_sms_single
from django.conf import settings


def send_sms(request):
    ''' 发送短信
        ?tpl=login -> 1744670
        ?tpl=register -> 1744672
        ?tpl=re_password -> 1744669
    '''
    tpl = request.GET.get('tpl')
    template_id = settings.TENCENT_SMS_TEMPLATE.get(tpl)
    if not template_id:
        return HttpResponse("模板不存在")
    code = random.randrange(1000, 9999)
    res = send_sms_single('18225078646', template_id, [code, ])
    if res['result'] == 0:
        return HttpResponse('成功')
    else:
        HttpResponse(res['errmsg'])


def register(request):
    form = RegisterModelForm()
    return render(request, 'register.html', {'form': form})

Web/views/register.py
# -*- coding:utf-8 -*-
import random

from django.http import JsonResponse
# Create your views here.
from django.shortcuts import HttpResponse, render

from Web.utils.ModelForm import *
from Web.utils.tencent.send_SMS import send_sms_single
from django.conf import settings


def send_sms(request):
    ''' 发送短信
        ?tpl=login -> 1744670
        ?tpl=register -> 1744672
        ?tpl=re_password -> 1744669
    '''
    form = SendSmsForm(request, data=request.GET)
    # 只是校验手机号:不能为空,格式是否正确
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})


def register(request):
    ''' 注册 '''
    form = RegisterModelForm()
    return render(request, 'register.html', {'form': form})

Web/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} }{% endblock %}</title>
    <!--引入css-->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <style>
        .navbar-default{
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tracer平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">产品功能</a></li>
                <li><a href="#">企业方案</a></li>
                <li><a href="#">帮助文档</a></li>
                <li><a href="#">价格</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{% block content %}{% endblock %}
<!--引入js-->
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

Web/templates/register.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}用户注册{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static  'css/account.css' %}">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="account">
            <div class="title">用户注册</div>
            <form id="form" method="post" novalidate>
                {% csrf_token %}
                {% for foo in form %}
                    {% if foo.name == 'code' %}
                        <div class="form-group">
                            <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                            <div class="clearfix">
                                <div class="col-md-7" style="padding-left: 0">{{ foo }}</div>
                                <div class="col-md-5">
                                    <input id="btnSms" type="button" class="btn btn-default" value="获取短信验证码">
                                </div>
                            </div>

                        </div>
                    {% else %}
                        <div class="form-group">
                            <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
                            {{ foo }}
                            <span class="error-msg">{{ foo.errors.0 }}</span>
                        </div>

                    {% endif %}
                {% endfor %}
                <button type="submit" style="margin-left: 100px;width: 120px" class="btn btn-info">注 册</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        // 页面框架加载完成后自动执行函数
        $(function () {
            bindClickBtnSms();
            window.history.replaceState(null, null, window.location.href);
        });

        /*
          点击获取短信验证码的按钮的绑定事件
        */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $('.error-msg').empty();
                // 获取用户输入的手机号
                // 找到输入框id,根据id获取值
                var mobilePhone = $('#id_mobile_phone').val();
                // 发送ajax请求,把手机号发送给后端
                $.ajax({
                    url: '{% url 'send_sms' %}',  //需要提交的地址 等价于/send/sms/
                    type: 'GET', //用什么方式传参
                    data: {mobile_phone: mobilePhone, tpl: 'register'},  //传递的参数
                    dataType: 'JSON', //将服务端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功后,自动执行的函数,res是后端返回的值
                        if (res.status) {
                            sendSmsRemind();
                        } else {
                            //错误信息
                            console.log(res)   // {status: false, error: {mobile_phone:['错误信息',]}}
                            $.each(res.error, function (key, value) {  //key:mobile_phone value:错误信息
                                $('#id_' + key).next().text(value[0]);  //向error-msg所在写入错误信息
                            })            //表示循环
                        }
                    }
                })
            })

            /*
                验证码过期倒计时
             */
            function sendSmsRemind() {
                var $smsBtn = $('#btnSms');
                $smsBtn.prop("disabled", true);  //添加disabled属性, 不可操作
                var time = 60;
                var remind = setInterval(function () {   //创建一个定时器
                    $smsBtn.val(time + '秒后可重新发送');
                    time = time - 1;
                    if (time === 0) {
                        clearInterval(remind);  //销毁定时器
                        $smsBtn.val('获取短信验证码').prop("disabled", false); //添加disabled属性, 可操作

                    }
                }, 1000)  //1000毫秒, 1秒
            }
        }
    </script>
{% endblock %}